server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/restaurant_db
    username: webuser
    password: webuser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  thymeleaf:
    cache: false

# JWT Configuration
jwt:
  secret: restaurantSecretKey
  expiration: 86400000 # 24 hours 